version: '3'

services:
  php:
    container_name: app
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: "remote_host={{host}} idekey={{key}} remote_port={{port}} remote_enable=1 remote_autostart=1"

  nginx:
    image: nginx:alpine
    ports:
      - 4000:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
